### ISSUE TITLE
Embedded video options?

### ISSUE THREAD

**Issue by kookster** [PRX/cms.theworld.org#106]
Sara asked: ```
Quick question… when WordPress does come around, do you know if we will have more video embedding options? Right now, we can only upload YouTube and Twitter in CMS.
```
https://prx.slack.com/archives/CR59F3MU2/p1685019827615059

**Comment by rpeterman-gp** [comment]
Per our video strategy meeting with editors, I am increasing the priority of this and adding to my current sprint.
