### ISSUE TITLE
Cleanup duplicate contextual tags applied to episodes

### ISSUE THREAD

**Issue by rpeterman-gp** [PRX/cms.theworld.org#122]
Currently there are base WP tags applied to posts and episodes that are also found in our contextual custom taxonomies, eg. `united-states`. Need to check each custom taxonomy term to see if it is a duplicate of a WP tag term (have the same name). If so, find all posts and episodes with the WP tag applied to it, apply the custom taxonomy term to the those posts, remove the WP tag from the posts, and finally delete the WP tag. This should prevent multiple tag landing pages for identical terms with differing post links.

**Comment by gtenaschuk** [comment]
@rpeterman-gp just to be sure about this.

1.  If we have a tag "United States" and we found the same name as part of any custom taxonomy term like country, states, social tags or any other. We must change the relationship from the tag to the custom taxonomy for all posts related to it and deleted the tag (we will do this in the last step where we are going to delete all the empty tags). 
2. Any tag with empty relations must be deleted.

**Comment by brandonhundt** [comment]
Closed with #156
