### ISSUE TITLE
Include ACF settings sync into dev scripts commands

### ISSUE THREAD

**Issue by rpeterman-gp** [PRX/cms.theworld.org#169]
We currently pull in CFM settings changes when running `npm run local` or `npm run refresh`. Would it be advisable to include synch ACF settings with these scripts as well?

Gist for plugin to add WP CLI command for ACF sync: https://gist.github.com/hirasso/c48c04def92f839f6264349a1be773b3

**Comment by brandonhundt** [comment]
Will add to Four Kitchens queue. Now that we aren't using WP-CFM, we should probably clean that out.

**Comment by gtenaschuk** [comment]
PR Added to include the WP-CLI command. The command needs to be run manually using wp-cli or terminus in pantheon environments.
```
 example usage wp-cli: wp tw acf-sync-field-groups
 example usage terminus: terminus wp the-world.{environemt} -- tw acf-sync-field-groups
```
