### ISSUE TITLE
Test Automatic Deploys

### ISSUE THREAD

**Issue by gtenaschuk** [PRX/cms.theworld.org#227]
Related to #WP-311 and #90 

- Push code to Pantheon Dev repository when pushing code or merging a PR to the main repo.
- Deploy code to Pantheon Test repository when pushing code  or merging a PR to the main repo and the commit message includes `[deploy:test]`
- Deploy code to Pantheon Live repository when pushing code  or merging a PR to the main repo and the commit message includes `[deploy:live]`
- Create a multidev environment based on live and push the code of that branch to Pantheon new environment when a branch name uses `multidev-` as prefix. 
For example `multidev-test` will try to create a multidev environment called `test` and then will push the code of the github branch to that environment. If a multidev environment already exists with that name, it is going to use the existing environment and push the branch code to it, forcing the update.

## To Review

- [x] Merge a PR to main
- [x] Go to https://dashboard.pantheon.io/sites/11e0e3e1-5d11-4a0e-8541-84d8ca4ce908#dev/code 
- [x] Check if the code was pushed to Dev environment

> ...then...

- [x] Merge a PR to main including `[deploy:test]` in the merge title.
- [x] Go to https://dashboard.pantheon.io/sites/11e0e3e1-5d11-4a0e-8541-84d8ca4ce908#test/code 
- [x] Check if the code was pushed to Dev environment and then deployed to Test Environment

> ...then...

- [x] Merge a PR to main including `[deploy:live]` in the merge title.
- [x] Go to https://dashboard.pantheon.io/sites/11e0e3e1-5d11-4a0e-8541-84d8ca4ce908#live/code 
- [x] Check if the code was pushed to Dev environment and then deployed to Test and Live Environments

> ...then...

- [x] Create a branch `multidev-prx` in the github online repository.
- [x] Go to https://dashboard.pantheon.io/sites/11e0e3e1-5d11-4a0e-8541-84d8ca4ce908#multidev/dev-environments
- [x] Check if the multidev environment `prx` was created with the github branch code merged on it.

**Comment by gtenaschuk** [comment]
@rpeterman-gp @brandonhundt 
Something to review about multidev feature. It is working but when you create a new branch the multidev environment creation is fired and the GH Action will wait for that creation to continue the merge code step. The thing with this is the time the Env takes to be created, if the GH Action waits for it, it will be a lot of use in your GH Actions time, and maybe will add extra costs in your invoice.
I would say that if we are gonna use the multidev it will be better to require the multidev env being created in Pantheon before using the branch deploy in GH. We can make the action fails if the multidev env does not exists and show the proper error message to say that it should exists in Pantheon.
Thoughts?

**Comment by gtenaschuk** [comment]
Automatic deploy to live worked properly
![Captura de pantalla 2024-10-01 a la(s) 18 10 08](https://github.com/user-attachments/assets/6612abd2-0878-44d4-ab81-03c8844f2236)
![Captura de pantalla 2024-10-01 a la(s) 18 11 37](https://github.com/user-attachments/assets/6c9a8498-d4fd-4f74-82ea-add2c151ffd1)

**Comment by brandonhundt** [comment]
^ #229 deployed to Test as expected. 👍

**Comment by gtenaschuk** [comment]
Great! i'm going to close this issue and the one in Clickup. Thanks!
