### ISSUE TITLE
R&D Import segments feed into WP

### ISSUE THREAD

**Issue by brandonhundt** [PRX/cms.theworld.org#41]
Like we do on the Drupal site, we need to import the audio segments feed into Wordpress. A bit of R&D ticket..

Options:
- Use a Paid Plugin
- RSS import
- API Import from Feeder

Goals:
- Auto Publishing of segments
- Episode import

**Comment by brandonhundt** [comment]
Create a "Dovetail API Integration" (Feeder API)
Aim for auto-publishing.

**Comment by rpeterman-gp** [comment]
Looks like we will be creating our own episode importer plugin since none of the RSS plugins out there allows use to do what we need. Closing this issue. Will open another issue for the plugin development.
