### ISSUE TITLE
R&D: Auto-tagging Posts

### ISSUE THREAD

**Issue by brandonhundt** [PRX/cms.theworld.org#43]
In the Drupal site we use Open Calais to autotag text text for tag suggestions. We'll need to look at similar solutions for Wordpress.

There are likely many options. Open to ideas.

**Comment by kookster** [comment]
these look interesting (and maybe the pro versions of them):
https://wordpress.org/plugins/simple-tags/
https://wordpress.org/plugins/laiser-tag/

Might also help with some of the taxonomy management
