### ISSUE TITLE
Research: Slow Performance on Pantheon Server

### ISSUE THREAD

**Issue by brandonhundt** [PRX/cms.theworld.org#74]
The admin is still super slow for posts on the live env in Pantheon. 

There are many options we could consider, but we should get advice from other Wordpressers. (Note: Advanced Page Cache with Pantheon is active.)

I just remember how the d8 cache module solved a lot of our Drupal performance issues, so something similar may be nice.

**Comment by brandonhundt** [comment]
I talked a little with our Pantheon rep about this. There's a chance the import script that syncs the drupal with wp live env may be causing an issue. They recommended this article: https://onlinemediamasters.com/slow-wordpress-admin-panel/

**Comment by gtenaschuk** [comment]
@brandonhundt one thing we saw a few days ago is the Admin Columns plugin doing some extra queries, sometimes those kind of plugins do their job and works good when you use them in small sites, but with a site like The World it could have unexpected results.
Another option for admin lists is enabling solr but it will need some configuration and tests to have it working properly with the fields and custom fields you want to use in the admin lists.

For post edit page we have a possible solution we can work on.

**Comment by brandonhundt** [comment]
Upgrading to "Elite" server seems to have resolved performance issues. If any further issue pop up we will create more specific tickets.
