### ISSUE TITLE
Admin UI for taxonomy, social tags uneditable due to slow loading

### ISSUE THREAD

**Issue by kookster** [PRX/cms.theworld.org#85]
from @rpeterman-gp:
 > I think we have too much data for WP to handle. It's frontend is not optimized for sites with lots of terms in a taxonomy. The Social Tags field is uneditable because before you can edit it, it has to load all 61K terms in that taxonomy (loaded 100 at a time via API requests). Each request for 100 terms takes ~2-3 seconds. That works out to somewhere between 20-30 minutes before the Social Tags fields gets rendered.

**Comment by brandonhundt** [comment]
https://advomatic.zendesk.com/hc/en-us/requests/8596
