### ISSUE TITLE
Clean up dupe taxonomies

### ISSUE THREAD

**Issue by kookster** [PRX/cms.theworld.org#86]
from: @rpeterman-gp 

> I just noticed that we have duplicate taxonomies, just slightly differently named:
> "Province or State" (province_state) and "Province Or State" (province_or_state)
> "Resource Development Tags" (resource_development_tag) and "Resource developments" (resource_development)
> "Social Tags" (social_tag) and "Social Tags" (social_tags)
> 
> Looks like we initially created some taxonomies, but the migration plugin creates its own version of those taxonomies.
> 
> I assume the ones created by the migration plugin would be the ones it uses to place the data.
>

**Comment by brandonhundt** [comment]
I've talked to Guillermo about this. He wants to leave them until we are fully done migrating (which means launch). He offered to send a note at which fields are the dupes. I can follow up on that.

**Comment by gtenaschuk** [comment]
Hey @rpeterman-gp and @brandonhundt For taxonomies, it will be good to keep the ones we migrated with the same names, and remove the duplicated ones that are empty. I can do that now if you are agree.
These are the ones i will remove when you confirm:

1. "Province or State" (province_state)
2. "Social Tags" (social_tag)
3. "Resource Development Tags" (resource_development_tag)

For duplicated information i want to keep:
1. Is related to Program and Person post types we moved them to Program and Contributor taxonomies. 
5. Is related with post meta information, we will keep the meta keys you added to the Google Sheet we used as key map when we started the migration, i will finish this doc by tomorrow to share with you. 

I'm planning to remove the post types and unused meta_keys just before the WP server is going to be used as Front End source. Sounds good?

**Comment by brandonhundt** [comment]
@gtenaschuk, yes please remove the fields you added for the migration. Its getting really hard for us to know which fields we should build the new frontend with. 

And if you want to keep the field or post type, can you add " - migration" label to the field? This way we know which will be the final field that is kept.

Thanks.

**Comment by gtenaschuk** [comment]
@brandonhundt a few things here:

1. I created a PR with changes in taxonomy definition to avoid duplicated ones. https://github.com/PRX/cms.theworld.org/pull/89
2. We are also working on this doc https://docs.google.com/spreadsheets/d/1vxtTrwttjhVynp_hak19lD-2fhgEeonkSxQBpbh5-Vw/edit#gid=1567704757 to show you the fields we are using and you can use from the API. We also added the list of unused metadata we are going to remove later and the metadata not used but we want to keep.
3. I'm adding the suffix "- Migration" to all the groups of custom fields in the UI we are not using so you don't need to pay attention to them.
4. I added the suffix "- Migration" to the Post types "Person" and "Program" so you know those ones are not going to be used and we are going to remove them when the migration is finished and you started using wordpress as source of the front end.

Let me know if you have questions or suggestions about this.
