### ISSUE TITLE
Undefined WP_ENVIRONMENT_TYPE

### ISSUE THREAD

**Issue by gtenaschuk** [PRX/cms.theworld.org#95]
Checking the logs to find code that could be causing slow performance i found this message related to an undefined constant used in production-config, it is a warning now but that will fire an error in future PHP version. 

`[14-Apr-2023 09:56:10 UTC] PHP Warning:  Use of undefined constant WP_ENVIRONMENT_TYPE - assumed 'WP_ENVIRONMENT_TYPE' (this will throw an Error in a future version of PHP) in /code/wp-content/mu-plugins/the-world-site-config/configs/production/production-config.php on line 19`

**Comment by brandonhundt** [comment]
@gtenaschuk @rpeterman-gp Do we need separate configs for 'staging'? We have global and production, so I'll remove the staging file in PR.
