### ISSUE TITLE
Audio media data missing duration

### ISSUE THREAD

**Issue by rpeterman-gp** [PRX/cms.theworld.org#96]
To be fair, not all audio in Drupal has a duration either (imported segment audio).

**Comment by gtenaschuk** [comment]
Hey @rpeterman-gp we didn't see any duration field as part of the import spreadsheet fields we needed to follow during migration, but as we have the Drupal file ID stored in the database we can run a new process to migrate the duration information if needed.

**Comment by brandonhundt** [comment]
Old stuff won't have durations, but new stuff will. Closing.
