### ISSUE TITLE
Convert all ACF reference fields to reference ID

### ISSUE THREAD

**Issue by rpeterman-gp** [PRX/cms.theworld.org#97]
ACF reference fields are always expanded and do not contain all needed data (ie. ACF fields on the reference), so additional requests would be needed. To lighten the payloads for ACF data, convert them to only return the reference ID.

**Comment by brandonhundt** [comment]
@rpeterman-gp I feel like you completed this one, yea? Close if true.

**Comment by rpeterman-gp** [comment]
This was partially done, but is irrelevant with the GraphQL API. Closing.
